ARG BASE_IMAGE="quay.io/fedora/fedora"
ARG BASE_VERSION="41"

FROM ${BASE_IMAGE}:${BASE_VERSION}

RUN dnf install -y \
        dnf-plugins-core \
    && dnf config-manager addrepo --from-repofile=https://pkgs.tailscale.com/stable/fedora/tailscale.repo \
    && dnf install -y \
        systemd tailscale \
    && dnf clean all \
    && systemctl enable tailscaled

#RUN [ -f /usr/bin/bootc ] && bootc container lint
