name: build containers (centos)
run-name: building containers (centos)
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run podman build - (centos) base
        run: |
          podman build -t ghcr.io/spotsnel/tailscale/centos:latest \
            --build-arg=BASE_IMAGE="quay.io/centos/centos" \
            --build-arg=BASE_VERSION="stream9" \
            -f containers/Containerfile-centos .
      - name: Run podman build - (centos-bootc) base
        run: |
          podman build -t ghcr.io/spotsnel/tailscale/centos-bootc:latest \
            --build-arg=BASE_IMAGE="quay.io/centos-bootc/centos-bootc" \
            --build-arg=BASE_VERSION="stream9" \
            -f containers/Containerfile-centos .
      - name: Push image to ghcr.io - (centos) base
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/spotsnel/tailscale/centos:latest
      - name: Push image to ghcr.io - (centos-bootc) base
        run: |
          podman push --creds=${{ github.actor }}:${{ secrets.GITHUB_TOKEN }} \
            ghcr.io/spotsnel/tailscale/centos-bootc:latest
